---
- name: Get Device Facts
  hosts: "vsrx-devices"
  connection: local
  gather_facts: false
  roles:
    - Juniper.junos

  vars:
    ansible_python_interpreter: /usr/bin/python3
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  tasks:
    - name: Shut down all REs
      juniper_junos_system:
        action: "shutdown"
        at: "now"
