---
- name: Get Device Facts
  hosts: "vsrx_devices"
  connection: local
  gather_facts: false
  roles:
    - Juniper.junos

  vars_prompt:
    - name: ADMPASS
      prompt: Password
      private: yes

  tasks:
    - name: Shut down all REs
      juniper_junos_system:
        host: "{{ ansible_host  }}"
        user: "{{ ansible_user  }}"
        passwd: "{{ ADMPASS  }}"
        action: "shutdown"
        at: "now"
